const ADD_ORDER = "ADD_ORDER";
const REMOVE_ORDER = "REMOVE_ORDER";
const CHANGE_LOGIN_STATUS = "CHANGE_LOGIN_STATUS";
const CHANGE_DISCOUNT = "CHANGE_DISCOUNT";

export { ADD_ORDER, REMOVE_ORDER, CHANGE_LOGIN_STATUS, CHANGE_DISCOUNT };
